## Enable dark theme "slate"  ##
- alias: 'Set tema til "slate"'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: slate

# Sensor control for lights
- alias: Sensorstyring av kjellerlys
  id: lys_gang_kjeller_sensor_paa
  trigger:
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    platform: state
    from: 'off'
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.qubino_zmnhadx_flush_1_relay_switch
    - delay: '00:30:00'
    - wait_template: "{{is_state('binary_sensor.aeotec_zw100_multisensor_6_sensor', 'off')}}"
    - service: switch.turn_off
      entity_id: switch.qubino_zmnhadx_flush_1_relay_switch

# Control Z-wave light dimmer with HUE Remote from Deconz
- alias: 'Toalett Oppe Lys På'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: toalett_oppe
      event: 1002
  action:
    service: light.turn_on
    entity_id: light.qubino_zmnhdd1_flush_dimmer_level
    data:
    # Brightness must be set to "kick" the light. If it is too dim the ligh will not go on.
      brightness: 100

- alias: 'Toalett Oppe Lys Av'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: toalett_oppe
      event: 4002
  action:
    service: light.turn_off
    entity_id: light.qubino_zmnhdd1_flush_dimmer_level

- alias: 'Increase brightness of lamp from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: toalett_oppe
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.qubino_zmnhdd1_flush_dimmer_level
        brightness: >
          {% set bri = states.light.qubino_zmnhdd1_flush_dimmer_level.attributes.brightness | int %}
          {{ [bri+30, 180] | min }}

- alias: 'Decrease brightness of lamp from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: toalett_oppe
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.qubino_zmnhdd1_flush_dimmer_level
        brightness: >
          {% set bri = states.light.qubino_zmnhdd1_flush_dimmer_level.attributes.brightness | int %}
          {{ [bri-30, 26] | max }}

# Porch light before sunset
- alias: 'Turn on porch lights before sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30'
  action:
    service: light.turn_on
    entity_id: light.inngangsparti
    data:
      brightness: 255

# turn off lights in the morning after sunrise
- alias: 'Turn off porch lights after sunrise'
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:30'
  action:
    service: light.turn_off
    entity_id: light.inngangsparti

# Turn off lights when no-one in livingroom and nighttime
- alias: 'Turn off porch lights when no motion and nighttime'
  trigger:
    platform: state
    entity_id: binary_sensor.presence_2
    to: 'off'
    for: 
      minutes: 15
  condition:
    condition: time
    after: '23:00'
  action:
    service: light.turn_off
    entity_id: light.inngangsparti  

- alias: Turn on porch lights if sun is set and motion
  trigger:
    platform: state
    entity_id: binary_sensor.presence_2
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    service: light.turn_on
    entity_id: light.inngangsparti  

# Automatic lock front door after 10 seconds
- alias: 'Lock door after 10 seconds'
  trigger:
    platform: state
    entity_id: lock.hoveddr
    from: 'locked'
    to: 'unlocked'
    for:
      seconds: 10
  action:
    service: lock.lock
    entity_id: lock.hoveddr
