## Enable dark theme "slate"  ##
- alias: 'Set tema til slate'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: slate

# Control Z-wave light dimmer with HUE Remote from Deconz
- alias: 'Toalett Oppe Lys På'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: toalett_oppe
      event: 1002
  action:
    service: light.turn_on
    entity_id: light.qubino_zmnhdd1_flush_dimmer_level
    data:
    # Brightness must be set to "kick" the light. If it is too dim the ligh will not go on.
      brightness: 100

- alias: 'Toalett Oppe Lys Av'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: toalett_oppe
      event: 4002
  action:
    service: light.turn_off
    entity_id: light.qubino_zmnhdd1_flush_dimmer_level

- alias: 'Increase brightness of lamp from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: toalett_oppe
      event: 2002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.qubino_zmnhdd1_flush_dimmer_level
        brightness: >
          {% set bri = states.light.qubino_zmnhdd1_flush_dimmer_level.attributes.brightness | int %}
          {{ [bri+30, 180] | min }}

- alias: 'Decrease brightness of lamp from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: toalett_oppe
      event: 3002
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.qubino_zmnhdd1_flush_dimmer_level
        brightness: >
          {% set bri = states.light.qubino_zmnhdd1_flush_dimmer_level.attributes.brightness | int %}
          {{ [bri-30, 26] | max }}

# Porch light before sunset
- alias: 'Turn on porch lights before sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30'
  action:
    service: light.turn_on
    entity_id: light.inngangsparti
    data:
      brightness: 255

# turn off lights in the morning after sunrise
- alias: 'Turn off porch lights after sunrise'
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:30'
  action:
    service: light.turn_off
    entity_id: light.inngangsparti

# Turn off lights when no-one in livingroom and nighttime
- alias: 'Turn off porch lights when no motion and nighttime'
  trigger:
    platform: state
    entity_id: binary_sensor.presence_2
    to: 'off'
    for: 
      minutes: 15
  condition:
    condition: time
    after: '23:00'
  action:
    service: light.turn_off
    entity_id: light.inngangsparti  

- alias: 'Turn on porch lights if sun is set and motion'
  trigger:
    platform: state
    entity_id: binary_sensor.presence_2
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    service: light.turn_on
    entity_id: light.inngangsparti  

# Automatic lock front door after 10 seconds
- alias: 'Lock door after 10 seconds'
  trigger:
    platform: state
    entity_id: lock.hoveddor
    from: 'locked'
    to: 'unlocked'
    for:
      seconds: 10
  action:
    service: lock.lock
    entity_id: lock.hoveddor

# Turn on light in the toilet if motion
- alias: 'Turn on toilet light when there is movement in hallway upstairs'
  trigger:
    platform: state
    entity_id: binary_sensor.presence_6
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.qubino_zmnhdd1_flush_dimmer_level

- alias: 'Turn off toilet light 15 minutes after last movement in hallway upstairs'
  trigger:
    platform: state
    entity_id: binary_sensor.presence_6
    to: 'off'
    for:
      minutes: 15
  action:
    service: light.turn_off
    entity_id: light.qubino_zmnhdd1_flush_dimmer_level

# Sensor control for lights in the hallway downstairs
- alias: 'Turn on hallway light downstairs when there is movement'
  trigger:
    platform: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.qubino_zmnhadx_flush_1_relay_switch

- alias: 'Turn off hallway light downstairs 15 minutes after last movement'
  trigger:
    platform: state
    entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
    to: 'off'
    for:
      minutes: 10
  action:
    service: switch.turn_off
    entity_id: switch.qubino_zmnhadx_flush_1_relay_switch

## Turn on nightmode for alarm when no movement in the house for 30 minutes
- alias: 'Turn on nightmode for alarm'
  trigger:
    platform: state # No movement upstairs for 15 minutes
    entity_id: binary_sensor.presence_2
    to: 'off'
    for:
      minutes: 15
  condition:
    condition: and
    conditions:
      - condition: time
        after: '23:00'
        before: '06:00'
      - condition: state # No movement downstairs for 30 minutes
        entity_id: binary_sensor.presence_6
        state: 'off'
        for:
          minutes: 30
  action:
    service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.sector_alarm_01603483
    data:
      code: !secret sector_code

## Turn off alarm nightmode on first movement upstairs
- alias: 'Turn off nightmode for alarm'
  trigger:
    platform: state
    entity_id: binary_sensor.presence_6
    to: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.sector_alarm_01603483
    state: 'armed_home'
  action:
    service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.sector_alarm_01603483
    data:
      code: !secret sector_code

## Turn on nightlight scene hallway when movement night
- alias: 'Nightlight upstairs hallway'
  trigger:
    platform: state
    entity_id: binary_sensor.presence_6
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.gang_oppe_trapp
        state: 'off'
        for:
          minutes: 1 # If manually turned off, delay to ensure movement does not turn it back on
      - condition: time
        after: '20:00'
        before: '08:00'
  action:
    service: scene.turn_on
    entity_id: scene.gang_oppe_nattlys


## Turn on light when movement
- alias: 'Normal-light upstairs hallway' 
  trigger:
    platform: state
    entity_id: binary_sensor.presence_6
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.gang_oppe_trapp
        state: 'off'
        for:
          minutes: 1 # If manually turned off, delay to ensure movement does not turn it back on
      - condition: time
        after: '08:00'
        before: '20:00'
  action:
    service: light.turn_on
    entity_id: light.gang_oppe
    data:
      brightness: '127'

## Dim light when no movement in hallway upstairs
- alias: 'Dim light when no movement in hallway' 
  trigger:
    platform: state
    entity_id: binary_sensor.presence_6
    to: 'off'
    for:
      minutes: 5    
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.gang_oppe_trapp
        state: 'on'
      - condition: time
        after: '08:00'
        before: '20:00'
  action:
    service: light.turn_on
    entity_id: light.gang_oppe
    data:
      brightness: '25'

## Dim light when no movement in hallway upstairs
- alias: 'Turn off nightlight hallway when no movement' 
  trigger:
    platform: state
    entity_id: binary_sensor.presence_6
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.gang_oppe_trapp
        state: 'on'
      - condition: time
        after: '20:00'
        before: '08:00'
  action:
    service: light.turn_off
    entity_id: light.gang_oppe
